### ISSUE TITLE
S7 don't connect anymore

### ISSUE THREAD

**Issue by LebretonGreg** [polygraphene/ALVR#19]
Hi, v1.7 didn't worked for me, after click connect, ALVR stopped on gear VR.
On v1.8 the connect button don't appear anymore, it stays stuck on "checking server status..."
Anyway, that's a great job you're doing, thanks!

**Comment by Lightsteed** [comment]
Did u update the client on the phone?

**Comment by LebretonGreg** [comment]
yes I did, it only works with server 1.7 and client 1.8 for a few seconds, I see the grids of steam VR then the client stop working on the phone and oculus home starts.

**Comment by polygraphene** [comment]
Thank you for comments!
Did you try to change the resolution or bitrate?
Lowering these values may help you.

If you got same error continuously, please send me the output of `adb logcat`.
Thanks.

**Comment by TerryXY** [comment]
Hey getting the same problem now on 1.8 - the server says its alive but on the server tab its just showing the server is not running, while the whole refresh spinner keeps spinning aswell. 

I'm on the oculus go. with version 1.7 i was able to see the connect button on the server tab, when i connected, the oculus go just kicked me back to the home screen. very few times i was able to see the actual steam vr room/grid for a few seconds before it booted me back to the oculus home screen.

Here is how it looks like right now 
![image](https://user-images.githubusercontent.com/4229187/40820194-516f7000-6589-11e8-910b-034843be66e9.png)

App is also updated, but i think its just an issue with the server app because now i cant even connect unlike before.

Driver is also installed according to the About tab

Any ideas? i will check for the logs

**Comment by polygraphene** [comment]
Thank you for detailed report!
Your log says that packet loss was occurred.
>06-01 10:56:11.895 16869 16887 V ALVR Native: Sending tracking info. FrameIndex=534
06-01 10:56:11.901 16869 16886 D ALVR Native: packet loss 9 (358921 -> 358929)
06-01 10:56:11.901 16869 16886 D ALVR Native: presentationTime end delay: 68986 us

And maybe the packet loss triggers exception in line 6992.
I will try to stabilize process processing.
Please wait a moment.

**Comment by polygraphene** [comment]
I have released v1.9.1 which contains the fix of packet processing.
Please try it.

**Comment by TerryXY** [comment]
Hey @polygraphene  just downloaded the latest. Still having the issue that the UI shows:
![image](https://user-images.githubusercontent.com/4229187/40879244-6f247200-66c7-11e8-9530-fc1da28dfd99.png)

even though SteamVR started and the server shows as alive. It also works on the  1.7 version. Just not on 1.8 and 1.9.X

**Comment by polygraphene** [comment]
Thank you for detailed debugging!
It is possible that other application use 9944/TCP port on your PC.

Please check it like following.
1. Open Task Manager and terminate vrserver.exe
2. Open command prompt with administrator and put `netstat -abnp TCP`.
3. Check if the line like following is displayed.
```
TCP         127.0.0.1:9944         0.0.0.0:0              LISTENING
```
or
```
TCP         0.0.0.0:9944         0.0.0.0:0              LISTENING
```

**Comment by TerryXY** [comment]
Hey, just checked. No other application is using them. The funny thing is it worked just fine on 1.7 - this started to happen on 1.8 and now also on 1.9.X

**Comment by polygraphene** [comment]
Weird...
When you start StreamVR manually, can you see the vrserver.exe is listening 9944 port?

**Comment by TerryXY** [comment]
![image](https://user-images.githubusercontent.com/4229187/40885058-9ce6d98a-6749-11e8-8f30-6dfd0bba867c.png)

its listed up 3 times - not sure if thats supposed to be like this haha. Anyway the socket also reports CONNECTED. I saw there are some changes with the whole buffer/parsing between 1.7 and 1.8 
I reverted the part where it uses the old way, it seems like it actually gets packets(using the reverted changes) but now the app doesnt understand them anymore i guess. 

Any other ideas?

**Comment by polygraphene** [comment]
Weird...
It should be one listning line...
How many vrserver.exe process on task manager?

If you can use telnet, close ALVR.exe and
put `telnet 127.0.0.1 9944` and then put `GetConfig` and press <Ctrl-J> on power shell.
It should be displayed like following.
![telnet](https://user-images.githubusercontent.com/2751376/40885221-277f0f6e-675d-11e8-970e-76e168dbfed3.png)

**Comment by TerryXY** [comment]
one only vrserver.exe task 
when i use telnet it just gets stuck here:
![image](https://user-images.githubusercontent.com/4229187/40885292-def519be-674d-11e8-859a-5cfb5d16f23a.png)

Cant send the GetConfig command

**Comment by polygraphene** [comment]
Did you uninstall old driver when upgrading?
If you have installed multiple drivers on different directory, it may cause an issue.
Please check `C:\Users\(usernaame)\AppData\Local\openvr\openvrpaths.vrpath` file.

**Comment by TerryXY** [comment]
Hah! That was it. I had multiple external driver entries in there. Thanks alot!  Going to test the latest version finally. Awesome job. Cheers!

**Comment by polygraphene** [comment]
Congratulations!
Thank you for a good work!

It was a hard to debug issue.
We should prohibit the duplicated driver installation to avoid this bug.
Thanks!
