### ISSUE TITLE
Stutters in Quest. 90Hz Vs 72Hz?

### ISSUE THREAD

**Issue by ElBatallitas** [polygraphene/ALVR#327]
I'm using this for Quest and I'm impressed by the image quality and low latency, yet I get lots of stutters no matter how much I lower the options. 
That led me into think it might be because the games are 90Hz and Quest display is 72Hz.
Is this something that could be fixed?

**Comment by magnoliafrost88** [comment]
This is something I wonder as well! Great question

**Comment by fdinsdale** [comment]
I know that on the version 2.3.X for the GO a change was made in the client to force 60FPS and that cleared up the stuttering. At 72FPS it was a stutterfest.

**Comment by magnoliafrost88** [comment]
But wait.... isn’t there a “force option to at least 60hz” in the client software now? It’s not optimal but that could maybe work? It can be found under [Other] in the app

**Comment by fdinsdale** [comment]
I don't know. I'm still using GO withe the old 2.3.X version. 

If the new client has that option try selecting it.

60FPS on the Go stopped the stuttering.

**Comment by magnoliafrost88** [comment]
I just tried but it didn’t really do any difference :/

**Comment by fdinsdale** [comment]
on the ALVR app on your PC the first tab (server), does it show you are connected at 72 or 60 FPS?

**Comment by magnoliafrost88** [comment]
72

**Comment by polygraphene** [comment]
I confirmed similar issue.
It seems that some frames are skipped (shows the same frame two-times) on client side.
Actual frame rate is dropping to 40~50fps and loses smoothness of animation.
I'm investigating the issue.

**Comment by ElBatallitas** [comment]
Great news! Thank you!!

**Comment by saintkamus** [comment]
> That led me into think it might be because the games are 90Hz and Quest display is 72Hz.
> Is this something that could be fixed?

The issue is not related to 90Hz, the games don't care about that. It looks like it's a problem with NVENC and only manifests itself at 72Hz. It's been like this since the Go came out.

On the Go, the fix was to use use a 60 Hz client someone forked, and it solved the issue.

I used to think it was because NVENC couldn't handle live streaming at more than 60 FPS, But devices like the nVidia shield can stream at 120 Hz, so It might just be a software problem (maybe driver related)

**Comment by saintkamus** [comment]
> 72

Quest doesn't support 60 Hz, at least not yet. John Carmack has confirmed that 60 Hz support is coming.

**Comment by ischicopter** [comment]
Same Problem here. Appears to happen only on Oculus titles through Revive. RoboRevive on the other hand works like a charm. No Problems with Steam Apps either.

It seems fine when remaining stationary. Moving objects are smooth as can be. But as soon as I move my head, things get stuttery/juddery. It is not a performance issue though, with the GPU being loaded at about 50%.


Apart from that, I am genuinely blown away by the streaming quality und low latency. 
I found these settings to work best for my setup: 
H.265
40 mbps
150% resolution in ALVR
100% resolution override in Steam VR

These will give around 60-80ms total latency and a stable stream.

Really impressed by the Quest‘s Display. Being able to boost it with supersampling from your PC beats Rift CV1 and Odyssey+, both of which I owned, by far in terms of overall sharpness and text readability.

I really hope the problem can be fixed soon.

Keep up the great work!

**Comment by ElBatallitas** [comment]
> Same Problem here. Appears to happen only on Oculus titles through Revive.

It also happens in Steam games

**Comment by ElBatallitas** [comment]
> > 72
> 
> Quest doesn't support 60 Hz, at least not yet. John Carmack has confirmed that 60 Hz support is coming.

That will be a solution to watch videos without stutter, but not for gaming... maybe for some stationary games only.

**Comment by ischicopter** [comment]
> > Same Problem here. Appears to happen only on Oculus titles through Revive.
> 
> It also happens in Steam games

Does it happen to you only when tracking or also when stationary?

**Comment by ElBatallitas** [comment]
> > > Same Problem here. Appears to happen only on Oculus titles through Revive.
> > 
> > 
> > It also happens in Steam games
> 
> Does it happen to you only when tracking or also when stationary?

Happens either way. Being stationary is less noticeable, not because the issue goes away, it's simply less noticeable.

**Comment by sbrierly** [comment]
Ishicopter's summary matches my experience quite a bit.  I played SteamVR Gorn and Brookhaven experiment and aside from the random slowdown every 10 minutes or so that lasted ~3 seconds, it was running near perfect and looked better than on my original Vive.  However, RoboRecall through Revive is stutter city.  It varies, sometimes it is not too bad, but other times it stutters like crazy.  Lowering the ALVR video stream to 8mbps did not improve things with RoboRecall.  I'll have to try RoboRevive!

**Comment by ElBatallitas** [comment]
>It looks like it's a problem with NVENC and only manifests itself at 72Hz. It's been like this since the Go came out.

That would make sense, so maybe the codec is not friendly with 72Hz. I'd like polygraphene to confirm this because looks complicated to report this to NVIDIA and have it fixed just for us.

**Comment by ischicopter** [comment]
QUOTE 
„Lowering the ALVR video stream to 8mbps did not improve things with RoboRecall. I'll have to try RoboRevive!“ 
QUOTE

You should feel a definite improvement, if you are in fact having the same issues as me. Keep us updated.

**Comment by sbrierly** [comment]
Only tried for about 5 minutes, but certainly seemed much smoother than playing through Revive!

**Comment by steeve** [comment]
@polygraphene I'm not sure this is fixed by reading the commits ? Perhaps via 424feecb7b065bd1d6a31b4ad8ab7745b28a6852 ?

**Comment by ischicopter** [comment]
Alpha5 seems to have fixed stutter in Elite Dangerous for me. It wouldn´t show more than 45-60 FPS in the Server Tab of ALVR. Now solid 72.

No improvement in OculusStore Games through Revive although it´s showing 72FPS.
RoboRevive still works fine. Could this be related to ASW, or incompatibility of it with Steam VR´s Reprojection?

**Comment by ElBatallitas** [comment]
Maybe got little bit better but I still get stutters since last update.

**Comment by ischicopter** [comment]
I noticed that resolution has a somewhat strange influence on framerate.

I can adjust resolution and ingame settings by trial and error to produce near 100% GPU usage with stable 72FPS to the Quest.
However, if I then crank up the resolution by just a little more, GPU usage will drop to around 70% and FPS 50-60. If I then take off the headset and wait for it to switch off it‘s displays, GPU-Usage will bump back up to 100% and 72FPS.

**Comment by piotr-j** [comment]
Latest prerelease of revive (1.7.0) improves the issue greatly. https://github.com/LibreVR/Revive/releases
According to revive dev its likely due to pose submission not being implemented by the driver. Latest release fakes this. This speculation is from revive discord, see https://gist.github.com/piotr-j/18ad4193d0eb95353ac671a82f572e45 for details

Perhaps this is just a coincidence, i have no idea what the driver actually does. Perhaps @polygraphene can confirm?

**Comment by sbrierly** [comment]
Awesome thanks... I'm seeing the same thing with 1.7.  Only tested RoboRecall and it was very smooth now.

**Comment by ischicopter** [comment]
> Awesome thanks... I'm seeing the same thing with 1.7. Only tested RoboRecall and it was very smooth now.

Agree. Seems to have fixed the stuttering when looking around. Still notice some stutter when moving around in the room though.

**Comment by ElBatallitas** [comment]
> Agree. Seems to have fixed the stuttering when looking around. Still notice some stutter when moving around in the room though. But definately an improvement.

Looking around you mean turning your head? because turning "in-game" meaning smooth turn or just turning the car in driving games, it also gives stutters, also when moving around as you say.

**Comment by ischicopter** [comment]
Yes i meant physically turning/tilting my head seems to work fine. But physically moving along the room, even inches, will still give stutter. It happens in Steam-Games like Elite Dangerous too, so it‘s probably a tracking-thing within ALVR.
