### ISSUE TITLE
Note 5 apk crashing (gear vr)

### ISSUE THREAD

**Issue by TyrannicalBlade** [polygraphene/ALVR#43]
The new ALVR 2.0 apk is crashing on note 5 and then it opens the Gear VR home. I am thinking it might be a building issue, but i tried rebuilding 1.9.2 and it worked.

**Comment by PURO-GOFIO** [comment]
i confirm that my s7 with gear dont open alvr 2.0...its crash when i put the phone in te gear headset

**Comment by iamapie13** [comment]
my s6 also crashes with the new 2.0 version, earlier versions work fine except for this one

**Comment by Tux0Topo** [comment]
Also mine S7 Exynos in developer mode and in headset crash too... Previous worked like charm...

**Comment by polygraphene** [comment]
Can you send the output of `adb logcat`?

**Comment by Tux0Topo** [comment]
[logcat.txt](https://github.com/polygraphene/ALVR/files/2092375/logcat.txt)
That helps?

**Comment by TyrannicalBlade** [comment]
[logcat.txt](https://github.com/polygraphene/ALVR/files/2092396/logcat.txt)

**Comment by polygraphene** [comment]
Thank you for the information!
The crash was caused by the decoder.
Startup optimization (https://github.com/polygraphene/ALVRClient/commit/ed55252f6a932b4b6c1b23e4e278c27bfba6af6c) may be bad for the decoder of Exynos devices.

I'll fix the issue.
Please wait a moment.

**Comment by polygraphene** [comment]
I've released the patched version.
Please try it.

**Comment by TyrannicalBlade** [comment]
Issue appears to still happen for me
[log_cat.txt](https://github.com/polygraphene/ALVR/files/2093928/log_cat.txt)

**Comment by Tux0Topo** [comment]
Still crashing...

**Comment by polygraphene** [comment]
Hmm...
Please try this again.
https://github.com/polygraphene/ALVRClient/releases/tag/v2.0.2
You can use server v2.0.1 with this client.

**Comment by TyrannicalBlade** [comment]
Working! Thanks for the quick updates!

**Comment by polygraphene** [comment]
Great!
Thank you for trying!

**Comment by Tux0Topo** [comment]
Just now could test it... Works perfect again! Thanks!!
